-- Kick Chat Activity System — shared multi-channel schema (CORE)
-- Run as a role with CREATE DATABASE privilege (e.g. ACCOUNTADMIN or SYSADMIN).
--
-- Existing AMIRPHANTHOM data: after this file, run sql/005_migrate_amirphanthom_to_core.sql

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS KICK_CHAT;
CREATE SCHEMA IF NOT EXISTS KICK_CHAT.CORE;

USE DATABASE KICK_CHAT;
USE SCHEMA CORE;

-- Tenant registry (Phase 2 multi-tenant). Default tenant holds all channels until orgs exist.
CREATE TABLE IF NOT EXISTS TENANTS (
    TENANT_ID           VARCHAR(64)     NOT NULL,
    DISPLAY_NAME        VARCHAR(256),
    STATUS              VARCHAR(32)     NOT NULL DEFAULT 'active',
    CREATED_AT          TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TENANTS PRIMARY KEY (TENANT_ID)
);

MERGE INTO TENANTS t
USING (SELECT 'default' AS TENANT_ID, 'Default operator' AS DISPLAY_NAME) s
ON t.TENANT_ID = s.TENANT_ID
WHEN NOT MATCHED THEN INSERT (TENANT_ID, DISPLAY_NAME) VALUES (s.TENANT_ID, s.DISPLAY_NAME);

-- Tracked Kick channels (streamer registry)
CREATE TABLE IF NOT EXISTS CHANNELS (
    CHANNEL_SLUG            VARCHAR(128)    NOT NULL,
    TENANT_ID               VARCHAR(64)     NOT NULL DEFAULT 'default',
    BROADCASTER_USER_ID     NUMBER,
    DISPLAY_NAME            VARCHAR(256),
    STATUS                  VARCHAR(32)     NOT NULL DEFAULT 'active',
    CHAT_SUBSCRIPTION_ID    VARCHAR(128),
    LIVESTREAM_SUBSCRIPTION_ID VARCHAR(128),
    CREATED_AT              TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT              TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CHANNELS PRIMARY KEY (CHANNEL_SLUG),
    CONSTRAINT FK_CHANNELS_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID)
);

-- Raw chat messages (idempotent on message_id)
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    MESSAGE_ID          VARCHAR(128)    NOT NULL,
    EVENT_MESSAGE_ID    VARCHAR(128),
    CHANNEL_SLUG        VARCHAR(128)    NOT NULL,
    BROADCASTER_USER_ID NUMBER,
    KICK_USER_ID        NUMBER          NOT NULL,
    USERNAME            VARCHAR(256)    NOT NULL,
    CONTENT             VARCHAR(8192),
    CREATED_AT          TIMESTAMP_TZ    NOT NULL,
    SOURCE              VARCHAR(32)     NOT NULL DEFAULT 'webhook',
    IS_COMMAND          BOOLEAN         DEFAULT FALSE,
    RAW_PAYLOAD         VARIANT,
    INGESTED_AT         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CHAT_MESSAGES PRIMARY KEY (MESSAGE_ID)
)
CLUSTER BY (CHANNEL_SLUG, CREATED_AT);

-- Per-channel chatter dimension (message counts are channel-scoped)
CREATE TABLE IF NOT EXISTS CHANNEL_USERS (
    CHANNEL_SLUG        VARCHAR(128)    NOT NULL,
    KICK_USER_ID        NUMBER          NOT NULL,
    USERNAME            VARCHAR(256)    NOT NULL,
    PROFILE_PICTURE     VARCHAR(1024),
    IS_VERIFIED         BOOLEAN         DEFAULT FALSE,
    FIRST_SEEN_AT       TIMESTAMP_TZ    NOT NULL,
    LAST_SEEN_AT        TIMESTAMP_TZ    NOT NULL,
    MESSAGE_COUNT       NUMBER          DEFAULT 0,
    CONSTRAINT PK_CHANNEL_USERS PRIMARY KEY (CHANNEL_SLUG, KICK_USER_ID)
);

-- Stream sessions from livestream.status.updated
CREATE TABLE IF NOT EXISTS STREAM_SESSIONS (
    SESSION_ID          VARCHAR(128)    NOT NULL,
    CHANNEL_SLUG        VARCHAR(128)    NOT NULL,
    BROADCASTER_USER_ID NUMBER,
    TITLE               VARCHAR(1024),
    STARTED_AT          TIMESTAMP_TZ    NOT NULL,
    ENDED_AT            TIMESTAMP_TZ,
    IS_LIVE             BOOLEAN         NOT NULL DEFAULT TRUE,
    RAW_PAYLOAD         VARIANT,
    INGESTED_AT         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STREAM_SESSIONS PRIMARY KEY (SESSION_ID)
)
CLUSTER BY (CHANNEL_SLUG, STARTED_AT);

-- Webhook delivery log for debugging / idempotency of event envelope
CREATE TABLE IF NOT EXISTS WEBHOOK_EVENTS (
    EVENT_MESSAGE_ID    VARCHAR(128)    NOT NULL,
    EVENT_TYPE          VARCHAR(128)    NOT NULL,
    EVENT_VERSION       VARCHAR(16),
    SUBSCRIPTION_ID     VARCHAR(128),
    CHANNEL_SLUG        VARCHAR(128),
    RECEIVED_AT         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PROCESSED_OK        BOOLEAN         DEFAULT TRUE,
    ERROR_MESSAGE       VARCHAR(2048),
    CONSTRAINT PK_WEBHOOK_EVENTS PRIMARY KEY (EVENT_MESSAGE_ID)
);

-- Seed first channel if missing (safe for fresh deploys)
MERGE INTO CHANNELS t
USING (
    SELECT
        'amirphanthom' AS CHANNEL_SLUG,
        'default' AS TENANT_ID,
        538671 AS BROADCASTER_USER_ID,
        'AmirPhanThom' AS DISPLAY_NAME
) s
ON t.CHANNEL_SLUG = s.CHANNEL_SLUG
WHEN NOT MATCHED THEN INSERT (
    CHANNEL_SLUG, TENANT_ID, BROADCASTER_USER_ID, DISPLAY_NAME
) VALUES (
    s.CHANNEL_SLUG, s.TENANT_ID, s.BROADCASTER_USER_ID, s.DISPLAY_NAME
);
