-- Kick Chat Activity System — AmirPhanThom
-- Run as a role with CREATE DATABASE privilege (e.g. ACCOUNTADMIN or SYSADMIN).

CREATE DATABASE IF NOT EXISTS KICK_CHAT;
CREATE SCHEMA IF NOT EXISTS KICK_CHAT.AMIRPHANTHOM;

USE DATABASE KICK_CHAT;
USE SCHEMA AMIRPHANTHOM;

-- Raw chat messages (idempotent on message_id)
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    MESSAGE_ID          VARCHAR(128)    NOT NULL,
    EVENT_MESSAGE_ID    VARCHAR(128),
    CHANNEL_SLUG        VARCHAR(128)    NOT NULL DEFAULT 'amirphanthom',
    BROADCASTER_USER_ID NUMBER,
    KICK_USER_ID        NUMBER          NOT NULL,
    USERNAME            VARCHAR(256)    NOT NULL,
    CONTENT             VARCHAR(8192),
    CREATED_AT          TIMESTAMP_TZ    NOT NULL,
    SOURCE              VARCHAR(32)     NOT NULL DEFAULT 'webhook',
    IS_COMMAND          BOOLEAN         DEFAULT FALSE,
    RAW_PAYLOAD         VARIANT,
    INGESTED_AT         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CHAT_MESSAGES PRIMARY KEY (MESSAGE_ID)
);

CREATE TABLE IF NOT EXISTS USERS (
    KICK_USER_ID        NUMBER          NOT NULL,
    USERNAME            VARCHAR(256)    NOT NULL,
    CHANNEL_SLUG        VARCHAR(128),
    PROFILE_PICTURE     VARCHAR(1024),
    IS_VERIFIED         BOOLEAN         DEFAULT FALSE,
    FIRST_SEEN_AT       TIMESTAMP_TZ    NOT NULL,
    LAST_SEEN_AT        TIMESTAMP_TZ    NOT NULL,
    MESSAGE_COUNT       NUMBER          DEFAULT 0,
    CONSTRAINT PK_USERS PRIMARY KEY (KICK_USER_ID)
);

-- Stream sessions from livestream.status.updated
CREATE TABLE IF NOT EXISTS STREAM_SESSIONS (
    SESSION_ID          VARCHAR(128)    NOT NULL,
    CHANNEL_SLUG        VARCHAR(128)    NOT NULL DEFAULT 'amirphanthom',
    BROADCASTER_USER_ID NUMBER,
    TITLE               VARCHAR(1024),
    STARTED_AT          TIMESTAMP_TZ    NOT NULL,
    ENDED_AT            TIMESTAMP_TZ,
    IS_LIVE             BOOLEAN         NOT NULL DEFAULT TRUE,
    RAW_PAYLOAD         VARIANT,
    INGESTED_AT         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STREAM_SESSIONS PRIMARY KEY (SESSION_ID)
);

-- Webhook delivery log for debugging / idempotency of event envelope
CREATE TABLE IF NOT EXISTS WEBHOOK_EVENTS (
    EVENT_MESSAGE_ID    VARCHAR(128)    NOT NULL,
    EVENT_TYPE          VARCHAR(128)    NOT NULL,
    EVENT_VERSION       VARCHAR(16),
    SUBSCRIPTION_ID     VARCHAR(128),
    RECEIVED_AT         TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PROCESSED_OK        BOOLEAN         DEFAULT TRUE,
    ERROR_MESSAGE       VARCHAR(2048),
    CONSTRAINT PK_WEBHOOK_EVENTS PRIMARY KEY (EVENT_MESSAGE_ID)
);
