-- Activity views for rewards / reporting / MCP queries
USE DATABASE KICK_CHAT;
USE SCHEMA AMIRPHANTHOM;

-- Daily activity per user (excludes command-only messages by default in leaderboard views)
CREATE OR REPLACE VIEW ACTIVITY_DAILY AS
SELECT
    KICK_USER_ID,
    USERNAME,
    CHANNEL_SLUG,
    DATE_TRUNC('DAY', CREATED_AT)::DATE AS ACTIVITY_DATE,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT_IF(NOT COALESCE(IS_COMMAND, FALSE)) AS NON_COMMAND_MESSAGE_COUNT,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
GROUP BY 1, 2, 3, 4;

-- Leaderboard: all-time (non-command messages)
CREATE OR REPLACE VIEW LEADERBOARD_ALL_TIME AS
SELECT
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
GROUP BY KICK_USER_ID
ORDER BY MESSAGE_COUNT DESC;

-- Leaderboard: last 7 days
CREATE OR REPLACE VIEW LEADERBOARD_7D AS
SELECT
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
  AND CREATED_AT >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
GROUP BY KICK_USER_ID
ORDER BY MESSAGE_COUNT DESC;

-- Leaderboard: last 30 days
CREATE OR REPLACE VIEW LEADERBOARD_30D AS
SELECT
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
  AND CREATED_AT >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
GROUP BY KICK_USER_ID
ORDER BY MESSAGE_COUNT DESC;

-- Messages attributed to known stream sessions (overlap on timestamp)
CREATE OR REPLACE VIEW ACTIVITY_BY_STREAM AS
SELECT
    s.SESSION_ID,
    s.TITLE AS STREAM_TITLE,
    s.STARTED_AT,
    s.ENDED_AT,
    m.KICK_USER_ID,
    m.USERNAME,
    COUNT(*) AS MESSAGE_COUNT
FROM STREAM_SESSIONS s
JOIN CHAT_MESSAGES m
  ON m.CHANNEL_SLUG = s.CHANNEL_SLUG
 AND m.CREATED_AT >= s.STARTED_AT
 AND (s.ENDED_AT IS NULL OR m.CREATED_AT <= s.ENDED_AT)
WHERE NOT COALESCE(m.IS_COMMAND, FALSE)
GROUP BY 1, 2, 3, 4, 5, 6;

-- Unique active stream-days per user (days with at least one non-command message during a session)
CREATE OR REPLACE VIEW STREAM_ACTIVE_DAYS AS
SELECT
    m.KICK_USER_ID,
    MAX(m.USERNAME) AS USERNAME,
    COUNT(DISTINCT DATE_TRUNC('DAY', s.STARTED_AT)::DATE) AS ACTIVE_STREAM_DAYS,
    COUNT(*) AS MESSAGES_DURING_STREAMS
FROM STREAM_SESSIONS s
JOIN CHAT_MESSAGES m
  ON m.CHANNEL_SLUG = s.CHANNEL_SLUG
 AND m.CREATED_AT >= s.STARTED_AT
 AND (s.ENDED_AT IS NULL OR m.CREATED_AT <= s.ENDED_AT)
WHERE NOT COALESCE(m.IS_COMMAND, FALSE)
GROUP BY m.KICK_USER_ID
ORDER BY ACTIVE_STREAM_DAYS DESC, MESSAGES_DURING_STREAMS DESC;
