-- Activity views for rewards / reporting / MCP (multi-channel CORE)
USE DATABASE KICK_CHAT;
USE SCHEMA CORE;

-- Daily activity per user per channel
CREATE OR REPLACE VIEW ACTIVITY_DAILY AS
SELECT
    CHANNEL_SLUG,
    KICK_USER_ID,
    USERNAME,
    DATE_TRUNC('DAY', CREATED_AT)::DATE AS ACTIVITY_DATE,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT_IF(NOT COALESCE(IS_COMMAND, FALSE)) AS NON_COMMAND_MESSAGE_COUNT,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
GROUP BY 1, 2, 3, 4;

-- Leaderboard: all-time per channel (non-command messages)
CREATE OR REPLACE VIEW LEADERBOARD_ALL_TIME AS
SELECT
    CHANNEL_SLUG,
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
GROUP BY CHANNEL_SLUG, KICK_USER_ID
ORDER BY CHANNEL_SLUG, MESSAGE_COUNT DESC;

-- Leaderboard: last 7 days per channel
CREATE OR REPLACE VIEW LEADERBOARD_7D AS
SELECT
    CHANNEL_SLUG,
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
  AND CREATED_AT >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
GROUP BY CHANNEL_SLUG, KICK_USER_ID
ORDER BY CHANNEL_SLUG, MESSAGE_COUNT DESC;

-- Leaderboard: last 30 days per channel
CREATE OR REPLACE VIEW LEADERBOARD_30D AS
SELECT
    CHANNEL_SLUG,
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
  AND CREATED_AT >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
GROUP BY CHANNEL_SLUG, KICK_USER_ID
ORDER BY CHANNEL_SLUG, MESSAGE_COUNT DESC;

-- Cross-channel: same Kick user across channels (operator analytics)
CREATE OR REPLACE VIEW USER_CHANNEL_ACTIVITY AS
SELECT
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    CHANNEL_SLUG,
    COUNT(*) AS MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
GROUP BY KICK_USER_ID, CHANNEL_SLUG
ORDER BY KICK_USER_ID, MESSAGE_COUNT DESC;

CREATE OR REPLACE VIEW USER_CROSS_CHANNEL_SUMMARY AS
SELECT
    KICK_USER_ID,
    MAX(USERNAME) AS USERNAME,
    COUNT(DISTINCT CHANNEL_SLUG) AS CHANNEL_COUNT,
    COUNT(*) AS TOTAL_MESSAGE_COUNT,
    COUNT(DISTINCT DATE_TRUNC('DAY', CREATED_AT)::DATE) AS ACTIVE_DAYS,
    MIN(CREATED_AT) AS FIRST_MESSAGE_AT,
    MAX(CREATED_AT) AS LAST_MESSAGE_AT
FROM CHAT_MESSAGES
WHERE NOT COALESCE(IS_COMMAND, FALSE)
GROUP BY KICK_USER_ID
ORDER BY TOTAL_MESSAGE_COUNT DESC;

-- Messages attributed to known stream sessions (overlap on timestamp)
CREATE OR REPLACE VIEW ACTIVITY_BY_STREAM AS
SELECT
    s.CHANNEL_SLUG,
    s.SESSION_ID,
    s.TITLE AS STREAM_TITLE,
    s.STARTED_AT,
    s.ENDED_AT,
    m.KICK_USER_ID,
    m.USERNAME,
    COUNT(*) AS MESSAGE_COUNT
FROM STREAM_SESSIONS s
JOIN CHAT_MESSAGES m
  ON m.CHANNEL_SLUG = s.CHANNEL_SLUG
 AND m.CREATED_AT >= s.STARTED_AT
 AND (s.ENDED_AT IS NULL OR m.CREATED_AT <= s.ENDED_AT)
WHERE NOT COALESCE(m.IS_COMMAND, FALSE)
GROUP BY 1, 2, 3, 4, 5, 6, 7;

-- Unique active stream-days per user per channel
CREATE OR REPLACE VIEW STREAM_ACTIVE_DAYS AS
SELECT
    m.CHANNEL_SLUG,
    m.KICK_USER_ID,
    MAX(m.USERNAME) AS USERNAME,
    COUNT(DISTINCT DATE_TRUNC('DAY', s.STARTED_AT)::DATE) AS ACTIVE_STREAM_DAYS,
    COUNT(*) AS MESSAGES_DURING_STREAMS
FROM STREAM_SESSIONS s
JOIN CHAT_MESSAGES m
  ON m.CHANNEL_SLUG = s.CHANNEL_SLUG
 AND m.CREATED_AT >= s.STARTED_AT
 AND (s.ENDED_AT IS NULL OR m.CREATED_AT <= s.ENDED_AT)
WHERE NOT COALESCE(m.IS_COMMAND, FALSE)
GROUP BY m.CHANNEL_SLUG, m.KICK_USER_ID
ORDER BY m.CHANNEL_SLUG, ACTIVE_STREAM_DAYS DESC, MESSAGES_DURING_STREAMS DESC;
