-- Migrate legacy KICK_CHAT.AMIRPHANTHOM → KICK_CHAT.CORE (idempotent)
-- Prerequisites: run sql/001_ddl.sql first (creates CORE + seed channel).
-- Safe to re-run: uses MERGE / NOT EXISTS patterns.

USE DATABASE KICK_CHAT;

-- Ensure CORE objects exist
CREATE SCHEMA IF NOT EXISTS KICK_CHAT.CORE;

-- Skip gracefully if legacy schema was never created
-- (operators running a fresh CORE-only deploy can ignore this file)

-- Channels seed from legacy messages if needed
MERGE INTO CORE.CHANNELS t
USING (
    SELECT
        'amirphanthom' AS CHANNEL_SLUG,
        'default' AS TENANT_ID,
        538671 AS BROADCASTER_USER_ID,
        'AmirPhanThom' AS DISPLAY_NAME
) s
ON t.CHANNEL_SLUG = s.CHANNEL_SLUG
WHEN NOT MATCHED THEN INSERT (
    CHANNEL_SLUG, TENANT_ID, BROADCASTER_USER_ID, DISPLAY_NAME
) VALUES (
    s.CHANNEL_SLUG, s.TENANT_ID, s.BROADCASTER_USER_ID, s.DISPLAY_NAME
);

-- Chat messages
MERGE INTO CORE.CHAT_MESSAGES t
USING (
    SELECT
        MESSAGE_ID,
        EVENT_MESSAGE_ID,
        COALESCE(CHANNEL_SLUG, 'amirphanthom') AS CHANNEL_SLUG,
        BROADCASTER_USER_ID,
        KICK_USER_ID,
        USERNAME,
        CONTENT,
        CREATED_AT,
        SOURCE,
        IS_COMMAND,
        RAW_PAYLOAD,
        INGESTED_AT
    FROM AMIRPHANTHOM.CHAT_MESSAGES
) s
ON t.MESSAGE_ID = s.MESSAGE_ID
WHEN NOT MATCHED THEN INSERT (
    MESSAGE_ID, EVENT_MESSAGE_ID, CHANNEL_SLUG, BROADCASTER_USER_ID,
    KICK_USER_ID, USERNAME, CONTENT, CREATED_AT, SOURCE, IS_COMMAND,
    RAW_PAYLOAD, INGESTED_AT
) VALUES (
    s.MESSAGE_ID, s.EVENT_MESSAGE_ID, s.CHANNEL_SLUG, s.BROADCASTER_USER_ID,
    s.KICK_USER_ID, s.USERNAME, s.CONTENT, s.CREATED_AT, s.SOURCE, s.IS_COMMAND,
    s.RAW_PAYLOAD, s.INGESTED_AT
);

-- Users → CHANNEL_USERS (legacy USERS were global; attribute to amirphanthom)
MERGE INTO CORE.CHANNEL_USERS t
USING (
    SELECT
        COALESCE(CHANNEL_SLUG, 'amirphanthom') AS CHANNEL_SLUG,
        KICK_USER_ID,
        USERNAME,
        PROFILE_PICTURE,
        IS_VERIFIED,
        FIRST_SEEN_AT,
        LAST_SEEN_AT,
        MESSAGE_COUNT
    FROM AMIRPHANTHOM.USERS
) s
ON t.CHANNEL_SLUG = s.CHANNEL_SLUG AND t.KICK_USER_ID = s.KICK_USER_ID
WHEN MATCHED THEN UPDATE SET
    USERNAME = s.USERNAME,
    PROFILE_PICTURE = COALESCE(s.PROFILE_PICTURE, t.PROFILE_PICTURE),
    IS_VERIFIED = s.IS_VERIFIED,
    LAST_SEEN_AT = GREATEST(t.LAST_SEEN_AT, s.LAST_SEEN_AT),
    MESSAGE_COUNT = GREATEST(t.MESSAGE_COUNT, s.MESSAGE_COUNT)
WHEN NOT MATCHED THEN INSERT (
    CHANNEL_SLUG, KICK_USER_ID, USERNAME, PROFILE_PICTURE, IS_VERIFIED,
    FIRST_SEEN_AT, LAST_SEEN_AT, MESSAGE_COUNT
) VALUES (
    s.CHANNEL_SLUG, s.KICK_USER_ID, s.USERNAME, s.PROFILE_PICTURE, s.IS_VERIFIED,
    s.FIRST_SEEN_AT, s.LAST_SEEN_AT, s.MESSAGE_COUNT
);

-- Stream sessions
MERGE INTO CORE.STREAM_SESSIONS t
USING (
    SELECT
        SESSION_ID,
        COALESCE(CHANNEL_SLUG, 'amirphanthom') AS CHANNEL_SLUG,
        BROADCASTER_USER_ID,
        TITLE,
        STARTED_AT,
        ENDED_AT,
        IS_LIVE,
        RAW_PAYLOAD,
        INGESTED_AT
    FROM AMIRPHANTHOM.STREAM_SESSIONS
) s
ON t.SESSION_ID = s.SESSION_ID
WHEN NOT MATCHED THEN INSERT (
    SESSION_ID, CHANNEL_SLUG, BROADCASTER_USER_ID, TITLE,
    STARTED_AT, ENDED_AT, IS_LIVE, RAW_PAYLOAD, INGESTED_AT
) VALUES (
    s.SESSION_ID, s.CHANNEL_SLUG, s.BROADCASTER_USER_ID, s.TITLE,
    s.STARTED_AT, s.ENDED_AT, s.IS_LIVE, s.RAW_PAYLOAD, s.INGESTED_AT
);

-- Webhook events
MERGE INTO CORE.WEBHOOK_EVENTS t
USING (
    SELECT
        EVENT_MESSAGE_ID,
        EVENT_TYPE,
        EVENT_VERSION,
        SUBSCRIPTION_ID,
        'amirphanthom' AS CHANNEL_SLUG,
        RECEIVED_AT,
        PROCESSED_OK,
        ERROR_MESSAGE
    FROM AMIRPHANTHOM.WEBHOOK_EVENTS
) s
ON t.EVENT_MESSAGE_ID = s.EVENT_MESSAGE_ID
WHEN NOT MATCHED THEN INSERT (
    EVENT_MESSAGE_ID, EVENT_TYPE, EVENT_VERSION, SUBSCRIPTION_ID,
    CHANNEL_SLUG, RECEIVED_AT, PROCESSED_OK, ERROR_MESSAGE
) VALUES (
    s.EVENT_MESSAGE_ID, s.EVENT_TYPE, s.EVENT_VERSION, s.SUBSCRIPTION_ID,
    s.CHANNEL_SLUG, s.RECEIVED_AT, s.PROCESSED_OK, s.ERROR_MESSAGE
);

-- Point app env at CORE after migration:
--   SNOWFLAKE_SCHEMA=CORE
-- Legacy AMIRPHANTHOM schema can be dropped later once verified:
--   DROP SCHEMA IF EXISTS KICK_CHAT.AMIRPHANTHOM CASCADE;
